### ISSUE TITLE
Updates to Faculty Handbook from Personnel Committee: Waiting for BoT approval

### ISSUE THREAD

**Issue by djp3** [djp3/WestmontFacultyHandbook#30]
These are recommendations from the Faculty Personnel Committee in an email 2/23/2022 to FacultyCouncil 

1. A change to the description of the committee’s responsibilities in 1.4.3.5.4 c)
We would like to strike 1) (“To interview and recommend to the Provost candidates for appointment to the faculty”) from the list. This has not been done for probably a decade or more now, and there does not seem to be a pressing need to reinstate the practice.

2. Five changes to 2.2.1.4

to reflect current practice
![Screen Shot 2022-03-07 at 18 02 00](https://user-images.githubusercontent.com/121683/157151382-2bd0d203-d7ca-4adc-8358-b18143421f30.png)

![Screen Shot 2022-03-07 at 18 02 24](https://user-images.githubusercontent.com/121683/157151425-19b76498-aaef-466b-b627-1c45db7f77a9.png)

 to strengthen our process
![Screen Shot 2022-03-07 at 18 01 31](https://user-images.githubusercontent.com/121683/157151325-20d09f0b-d023-4087-8627-8682cbc4d406.png)

![Screen Shot 2022-03-07 at 18 01 00](https://user-images.githubusercontent.com/121683/157151261-090a8b5c-9e85-4864-a2c0-24213a41a70f.png)

![Screen Shot 2022-03-07 at 18 00 26](https://user-images.githubusercontent.com/121683/157151192-0e222cf2-77bd-4915-b5a2-2494d2beb72b.png)

![Screen Shot 2022-03-07 at 18 02 59](https://user-images.githubusercontent.com/121683/157151479-aab9a586-3a5c-4898-b52e-bd09b567ab90.png)

**Comment by djp3** [comment]
Update from executive session from Alistair Chapman:
modifying the search committee choice... need more details.

**Comment by djp3** [comment]
consult with provost about external personnel assignment to committees

**Comment by djp3** [comment]
Motion approved at Faculty Meeting.
Waiting for Board of Trustees approval.

**Comment by amaspark** [comment]
This has been approved by the Board of Trustees.
